%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\bryni\OneDrive\Skrivebord\sensor-lab\test.bin.csv
%
% Auto-generated by MATLAB on 03-Feb-2025 12:43:38

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "Channel1", "Channel2", "Channel3", "Channel4", "Channel5"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
test = readtable("C:\Users\bryni\OneDrive\Skrivebord\sensor-lab\test.bin.csv", opts);


%% Clear temporary variables
clear opts 

for i = 2:6
    test{1,i} = test{2,i};
end



[Auto,lags] = autocorr(test.Channel1);
[xross, lags0] = xcorr(test.Channel1, test.Channel2);

%plot(test.Time, test.Channel1)
stem(lags0, xross);

[Maks, indeks] = max(xross)